approvals:
  minimum: 1
  ignore: none
  pattern: "^(:\\+1:|👍)$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|👎)$"
linkticket:
  url: "https://github.com/${owner}/${repo}/issues"
  pattern: "^#([0-9]+)"
